#steps:

#- name: gcr.io/cloud-builders/npm
#  args: [ install ]

#- name: gcr.io/cloud-builders/npm
#  args: [ run, build, --prod ]

#- name: gcr.io/cloud-builders/gcloud
#  args: [ app, deploy ]

steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloudrun-demo:${SHORT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/cloudrun-demo"]
